[package]
edition = "2021"
license = "GPL-3.0"
name = "desktop_objc"
version = "0.0.0"
publish = false

[features]
default = []

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tokio.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "=0.10.0"

[build-dependencies]
cc = "=1.2.4"
glob = "=0.3.2"
